import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
 

  cssSidebar: [
    {
      type: 'autogenerated',
      dirName: '1.Css', 
    },
  ],
  
  javascriptSidebar: [
    {
      type: 'autogenerated',
      dirName: '2.javascript', 
    },
  ],
  reactSidebar: [
    {
      type: 'autogenerated',
      dirName: '3.react', 
    },
  ],
  nextjsSidebar: [
    {
      type: 'autogenerated',
      dirName: '4.next-js', 
    },
  ],
  typescriptSidebar: [
    {
      type: 'autogenerated',
      dirName: '5.typescript', 
    },
  ],
  nodeexpressSidebar: [
    {
      type: 'autogenerated',
      dirName: '6.node-express', 
    },
  ],
  databasesSidebar: [
    {
      type: 'autogenerated',
      dirName: '7.databases', 
    },
  ],
  redisSidebar: [
    {
      type: 'autogenerated',
      dirName: '8.Redis', 
    },
  ],
  elasticsearchSidebar: [
    {
      type: 'autogenerated',
      dirName: '9.ElasticSearch', 
    },
  ],
};

export default sidebars;
